{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.config.dbtestapp.deploy }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: dbtestapp
  labels:
{{ tuple "dbtestapp" . | include "5g-test-apps.metadata_labels" | indent 4 }}
data:
  dbtestapp-run.sh: |
{{ tuple "bin/_dbtestapp-run.sh.tpl" . | include "5g-test-apps.template" | indent 4 }}
{{- if not .Values.config.useExistingConfigMap -}}
{{- range $key, $value := .Values.config.dbtestapp.cfgFiles }}
  {{ $key }}: |-
{{ toYaml $value | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
