# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

images:
  repository: "" # default docker hub 
  tags:
    dbtestapp: "omecproject/dbtestapp:0.0.1-dev"
  pullPolicy: IfNotPresent

mongodb:
  deploy: true
  fullnameOverride: mongodb
  persistence:
    enabled: false
  auth:
    enabled: false
  serviceAccount:
    create: false

resources:
  enabled: false
  dbtestapp:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

config:
  coreDump:
    enabled: false
    path: /tmp/coredump
  dbtestapp:
    deploy: true
    serviceType: ClusterIP
    replica: 1
    httpServer:
      enable: true
      port: 8000
