# SPDX-FileCopyrightText: {C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: router-net
{{- if eq .Values.config.router.cni "sriov" }}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{ .Values.config.router.resourceName }}
{{- end }}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "{{ .Values.config.router.cni }}",
  {{- if eq .Values.config.router.cni "macvlan" }}
    "master": "{{ .Values.config.router.dataIface }}",
  {{- end }}
    "ipam": {
        "type": "static"
    }
  }'
